# CD workflow for React app

name: React App CD

on:
  push:
    branches:
    - main
    - releases/*

env:
  owner: <owner>
  domain: github.io
  
jobs: 
  deploy-dev-test: 
    env: 
      repo: ci-cd-with-actions
    environment: 
      name: DevTest
      url: "https://${{ env.owner }}.${{ env.domain }}/${{ env.repo }}//"
    name: "Deploy to Dev test environment"
    runs-on: ubuntu-latest
    steps: 
      - 
        name: Checkout
        uses: actions/checkout@v2.3.1
      - 
        name: "Install and Build"
        run: |
            npm install
            npm run build
      - 
        name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with: 
          branch: gh-pages
          folder: build
